{"data": [
{"status": "RUNNING", "run_id": "c6068f4861", "start_time": "16-11-23 00:01:34", "project": "treehouse", "donor_id": "S1022777", "pipeline_name": "RNAseq", "sample_id": "S1022777c4", "error_text": null},
{"status": "FAILED", "run_id": "b54c274a8d", "start_time": "16-11-23 00:01:55", "project": "treehouse", "donor_id": "S3150095", "pipeline_name": "RNAseq", "sample_id": "S3150095a1", "error_text": "\"Runtime error:\\nTraceback (most recent call last):\\n  File \\\"/home/hancock/analysis_core/env/local/lib/python2.7/site-packages/luigi/worker.py\\\", line 192, in run\\n    new_deps = self._run_get_new_deps()\\n  File \\\"/home/hancock/analysis_core/env/local/lib/python2.7/site-packages/luigi/worker.py\\\", line 130, in _run_get_new_deps\\n    task_gen = self.task.run()\\n  File \\\"/home/hancock/analysis_core/dashboard-service/luigi-interface/spawned.py\\\", line 19, in run\\n    raise Exception(\\\"This was a failure.\\\")\\nException: This was a failure.\\n\""},
{"status": "FAILED", "run_id": "ec3594f08d", "start_time": "16-11-23 00:01:24", "project": "treehouse", "donor_id": "S1427920", "pipeline_name": "RNAseq", "sample_id": "S1427920b2", "error_text": "\"Runtime error:\\nTraceback (most recent call last):\\n  File \\\"/home/hancock/analysis_core/env/local/lib/python2.7/site-packages/luigi/worker.py\\\", line 192, in run\\n    new_deps = self._run_get_new_deps()\\n  File \\\"/home/hancock/analysis_core/env/local/lib/python2.7/site-packages/luigi/worker.py\\\", line 130, in _run_get_new_deps\\n    task_gen = self.task.run()\\n  File \\\"/home/hancock/analysis_core/dashboard-service/luigi-interface/spawned.py\\\", line 19, in run\\n    raise Exception(\\\"This was a failure.\\\")\\nException: This was a failure.\\n\""},
{"status": "FAILED", "run_id": "c9453e7f29", "start_time": "16-11-23 00:01:44", "project": "treehouse", "donor_id": "S6429996", "pipeline_name": "RNAseq", "sample_id": "S6429996b4", "error_text": "\"Runtime error:\\nTraceback (most recent call last):\\n  File \\\"/home/hancock/analysis_core/env/local/lib/python2.7/site-packages/luigi/worker.py\\\", line 192, in run\\n    new_deps = self._run_get_new_deps()\\n  File \\\"/home/hancock/analysis_core/env/local/lib/python2.7/site-packages/luigi/worker.py\\\", line 130, in _run_get_new_deps\\n    task_gen = self.task.run()\\n  File \\\"/home/hancock/analysis_core/dashboard-service/luigi-interface/spawned.py\\\", line 19, in run\\n    raise Exception(\\\"This was a failure.\\\")\\nException: This was a failure.\\n\""},
{"status": "FAILED", "run_id": "84d6699aee", "start_time": "16-11-23 00:02:05", "project": "treehouse", "donor_id": "S1060221", "pipeline_name": "RNAseq", "sample_id": "S1060221a2", "error_text": "\"Runtime error:\\nTraceback (most recent call last):\\n  File \\\"/home/hancock/analysis_core/env/local/lib/python2.7/site-packages/luigi/worker.py\\\", line 192, in run\\n    new_deps = self._run_get_new_deps()\\n  File \\\"/home/hancock/analysis_core/env/local/lib/python2.7/site-packages/luigi/worker.py\\\", line 130, in _run_get_new_deps\\n    task_gen = self.task.run()\\n  File \\\"/home/hancock/analysis_core/dashboard-service/luigi-interface/spawned.py\\\", line 19, in run\\n    raise Exception(\\\"This was a failure.\\\")\\nException: This was a failure.\\n\""},
{"status": "DONE", "run_id": "21d099ea75", "start_time": "16-11-23 00:01:49", "project": "treehouse", "donor_id": "S8669900", "pipeline_name": "RNAseq", "sample_id": "S8669900a3", "error_text": null},
{"status": "DONE", "run_id": "cbe43d0c6e", "start_time": "16-11-23 00:02:00", "project": "treehouse", "donor_id": "S1464980", "pipeline_name": "RNAseq", "sample_id": "S1464980a2", "error_text": null},
{"status": "DONE", "run_id": "8feeb700d9", "start_time": "16-11-23 00:01:29", "project": "treehouse", "donor_id": "S6006629", "pipeline_name": "RNAseq", "sample_id": "S6006629a2", "error_text": null},
{"status": "DONE", "run_id": "1a4caceeee", "start_time": "16-11-23 00:01:39", "project": "treehouse", "donor_id": "S2978057", "pipeline_name": "RNAseq", "sample_id": "S2978057a5", "error_text": null},
{"status": "DONE", "run_id": "df64a60463", "start_time": "16-11-23 00:02:10", "project": "treehouse", "donor_id": "S4318804", "pipeline_name": "RNAseq", "sample_id": "S4318804b4", "error_text": null}
]}
